version: '3'

services:

  pokerman:
    container_name: pokerman
    restart: always
    build:
      context: ./pokerman
    hostname: pokerman
    ports:
      - 20000:20000
    networks:
      - backend

  db-pokerman:
    container_name: pokerman
    restart: always
    image: postgres:12.2-alpine
    hostname: pokerman
    volumes:
      - db-pokerman:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pokerman
      - POSTGRES_PASSWORD=pokerman
      - POSTGRES_DB=pokerman
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-pokerman:
