version: '3'

services:

  poker-chpoker:
    container_name: poker-chpoker
    restart: always
    build:
      context: ./poker-chpoker
    hostname: poker-chpoker
    ports:
      - 20000:20000
    networks:
      - backend

  db-poker-chpoker:
    container_name: poker-chpoker
    restart: always
    image: postgres:12.2-alpine
    hostname: poker-chpoker
    volumes:
      - db-poker-chpoker:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=poker-chpoker
      - POSTGRES_PASSWORD=poker-chpoker
      - POSTGRES_DB=poker-chpoker
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-poker-chpoker:
